"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, FileText, Landmark, TrendingUp, Wallet } from "lucide-react";
import { InvestorShell } from "@/components/investor/InvestorShell";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { formatFCFA, formatRate } from "@/lib/calculations";

type Mode="investments"|"payments"|"documents"|"withdrawal";
type Payment={id:string;reference:string;amount:number;method:string;status:string;createdAt:string};
type Investment={id:string;amount:number;status:string;createdAt:string;paidAt:string|null;offer:{id:string;type:string;rate:number;ratePeriod:string;duration:number;project:{title:string;sector:string;company:{name:string}}};payments:Payment[]};
type Distribution={id:string;capitalAmount:number;interestAmount:number;status:string;withdrawnAt:string|null;createdAt:string;repayment:{scheduleDate:string;offer:{project:{title:string}}};investment:{id:string;amount:number}};
type KycDoc={id:string;type:string;fileName:string;fileSize:number|null;status:string;uploadedAt:string;verifiedAt:string|null};
type Kyc={kycStatus:string;kycDocuments:KycDoc[]};

const META:Record<Mode,{title:string;subtitle:string}>={investments:{title:"Investissements",subtitle:"Capital engagé, statut de chaque souscription et conditions contractuelles."},payments:{title:"Paiements",subtitle:"Engagements, références, moyens de paiement et confirmations serveur."},documents:{title:"Documents",subtitle:"Vos justificatifs de vérification et les documents réellement disponibles sur le compte."},withdrawal:{title:"Versements",subtitle:"Distinguez les sommes disponibles sur la plateforme des versements externes réellement exécutés."}};

export function InvestorFinanceModule({mode}:{mode:Mode}){const[investments,setInvestments]=useState<Investment[]>([]);const[distributions,setDistributions]=useState<Distribution[]>([]);const[kyc,setKyc]=useState<Kyc|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const load=async()=>{setLoading(true);try{const[ir,dr,kr]=await Promise.all([fetch('/api/investments'),fetch('/api/distributions'),fetch('/api/kyc')]);if(ir.ok)setInvestments(await ir.json());if(dr.ok)setDistributions(await dr.json());if(kr.ok)setKyc(await kr.json())}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const payments=useMemo(()=>investments.flatMap(i=>i.payments.map(p=>({...p,company:i.offer.project.company.name,project:i.offer.project.title,investmentId:i.id}))).sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt)),[investments]);const available=distributions.filter(d=>d.status==='AVAILABLE');const pending=distributions.filter(d=>d.status==='WITHDRAWAL_PENDING');const withdrawn=distributions.filter(d=>d.status==='WITHDRAWN');const availableTotal=available.reduce((s,d)=>s+d.capitalAmount+d.interestAmount,0);const pendingTotal=pending.reduce((s,d)=>s+d.capitalAmount+d.interestAmount,0);const withdrawnTotal=withdrawn.reduce((s,d)=>s+d.capitalAmount+d.interestAmount,0);
 const requestWithdrawal=async()=>{if(!available.length)return;setMessage('');const r=await fetch('/api/distributions/withdraw',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({distributionIds:available.map(d=>d.id)})});const j=await r.json().catch(()=>({}));if(!r.ok){setMessage(j.error||'Demande impossible');return}setMessage(`Demande enregistrée : ${formatFCFA(j.amount||0)} est désormais réservé pour vérification du versement externe.`);await load()};
 if(loading)return <InvestorShell title={META[mode].title} subtitle={META[mode].subtitle}><div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="nx-skeleton h-28"/>)}</div></InvestorShell>;
 let content:React.ReactNode;
 if(mode==='investments')content=<div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="Capital confirmé" value={formatFCFA(investments.filter(i=>i.status==='CONFIRMED').reduce((s,i)=>s+i.amount,0))}/><Metric label="Souscriptions en attente" value={String(investments.filter(i=>i.status==='PENDING').length)}/><Metric label="Opérations" value={String(investments.length)}/></div><div className="grid gap-4 xl:grid-cols-2">{investments.map(i=><Card key={i.id}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-[#507300]">{i.offer.project.sector}</p><h2 className="mt-1 text-lg font-bold">{i.offer.project.company.name}</h2><p className="text-sm text-[#101010]/55">{i.offer.project.title}</p></div><StatusBadge status={i.status}/></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="Capital" value={formatFCFA(i.amount)}/><Mini label={i.offer.type==='DEBT'?'Taux':'Part'} value={formatRate(i.offer.rate)}/><Mini label="Durée" value={`${i.offer.duration} mois`}/><Mini label="Paiements" value={String(i.payments.length)}/></div><Link href={`/offres/${i.offer.id}`}><Button variant="secondary" size="sm" className="mt-4">Voir l'offre <ArrowRight className="h-4 w-4"/></Button></Link></Card>)}{!investments.length&&<Empty title="Aucun investissement" text="Explorez les offres pour construire votre portefeuille." href="/offres"/>}</div></div>;
 else if(mode==='payments')content=<div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="Confirmé" value={formatFCFA(payments.filter(p=>p.status==='CONFIRMED').reduce((s,p)=>s+p.amount,0))}/><Metric label="En attente" value={formatFCFA(payments.filter(p=>p.status==='PENDING').reduce((s,p)=>s+p.amount,0))}/><Metric label="Références" value={String(payments.length)}/></div><Card><h2 className="mb-4 text-lg font-bold">Historique des paiements</h2><div className="divide-y divide-[#101010]/7">{payments.map(p=><div key={p.id} className="grid gap-2 py-3.5 sm:grid-cols-[1.3fr_.7fr_.6fr_auto] sm:items-center"><div><p className="text-sm font-semibold">{p.company}</p><p className="text-xs text-[#101010]/45">{p.reference} · {p.method}</p></div><p className="text-sm font-bold">{formatFCFA(p.amount)}</p><p className="text-xs text-[#101010]/45">{new Date(p.createdAt).toLocaleString('fr-FR')}</p><StatusBadge status={p.status}/></div>)}{!payments.length&&<p className="py-10 text-center text-sm text-[#101010]/45">Aucun paiement.</p>}</div></Card></div>;
 else if(mode==='documents')content=<div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="État de vérification" value={kyc?.kycStatus||'—'}/><Metric label="Documents fournis" value={String(kyc?.kycDocuments.length||0)}/><Metric label="Vérifiés" value={String(kyc?.kycDocuments.filter(d=>d.status==='VERIFIED').length||0)}/></div><Card><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Justificatifs de compte</h2><Link href="/verification"><Button size="sm" variant="secondary">Gérer la vérification</Button></Link></div><div className="divide-y divide-[#101010]/7">{kyc?.kycDocuments.map(d=><div key={d.id} className="flex items-center justify-between gap-4 py-3.5"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[12px] bg-[#EFFBDD]"><FileText className="h-4 w-4"/></span><div className="min-w-0"><p className="truncate text-sm font-semibold">{d.fileName}</p><p className="text-xs text-[#101010]/45">{d.type} · {new Date(d.uploadedAt).toLocaleDateString('fr-FR')}</p></div></div><StatusBadge status={d.status}/></div>)}{!kyc?.kycDocuments.length&&<p className="py-10 text-center text-sm text-[#101010]/45">Aucun justificatif enregistré.</p>}</div></Card><Card><p className="text-sm leading-relaxed text-[#101010]/60"><b>Documents contractuels :</b> le modèle de données actuel ne contient pas encore un coffre documentaire versionné pour contrats signés, notes d'information et attestations fiscales. L'interface ne fabrique donc aucun faux PDF. Cette couche doit être branchée à un stockage privé avant usage réel.</p></Card></div>;
 else content=<div className="space-y-5">{message&&<div className="rounded-[14px] border border-[#101010]/8 bg-white p-3 text-sm">{message}</div>}<div className="grid gap-4 md:grid-cols-3"><Metric label="Disponible" value={formatFCFA(availableTotal)}/><Metric label="Réservé pour versement" value={formatFCFA(pendingTotal)}/><Metric label="Versé extérieurement" value={formatFCFA(withdrawnTotal)}/></div><div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><Card><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Droits investisseurs</h2><Badge variant="accent">{distributions.length} ligne(s)</Badge></div><div className="divide-y divide-[#101010]/7">{distributions.map(d=><div key={d.id} className="flex items-start justify-between gap-4 py-3.5"><div><p className="text-sm font-semibold">{d.repayment.offer.project.title}</p><p className="text-xs text-[#101010]/45">Capital {formatFCFA(d.capitalAmount)} · rémunération {formatFCFA(d.interestAmount)}</p></div><StatusBadge status={d.status}/></div>)}{!distributions.length&&<p className="py-10 text-center text-sm text-[#101010]/45">Aucun montant distribuable.</p>}</div></Card><Card><Wallet className="h-5 w-5"/><h2 className="mt-3 font-bold">Demander un versement</h2><p className="mt-2 text-sm leading-relaxed text-[#101010]/60">La demande réserve le solde disponible. Elle ne devient « versée » qu'après confirmation externe. En mode démonstration, aucun transfert bancaire ou Mobile Money réel n'est exécuté.</p><Button className="mt-5 w-full" disabled={!available.length} onClick={()=>void requestWithdrawal()}>Demander {formatFCFA(availableTotal)}</Button></Card></div></div>;
 return <InvestorShell title={META[mode].title} subtitle={META[mode].subtitle}>{content}</InvestorShell>}
function Metric({label,value}:{label:string;value:string}){return <Card><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#101010]/42">{label}</p><p className="mt-2 text-xl font-bold tracking-[-.03em] sm:text-2xl">{value}</p></Card>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-[12px] bg-[#F5F5F3] p-3"><p className="text-[10px] uppercase tracking-wide text-[#101010]/40">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>}
function Empty({title,text,href}:{title:string;text:string;href:string}){return <Card className="text-center xl:col-span-2"><TrendingUp className="mx-auto h-6 w-6 text-[#101010]/25"/><h2 className="mt-3 font-bold">{title}</h2><p className="mt-1 text-sm text-[#101010]/50">{text}</p><Link href={href}><Button className="mt-5">Explorer</Button></Link></Card>}
