"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Bell, ChevronRight, FileText, Globe2, KeyRound, Landmark, Languages, ShieldCheck, UserRound, WalletCards } from "lucide-react";
import { AppHeader } from "@/components/AppHeader";
import { Button } from "@/components/ui/Button";
import { Card, CardHeader, CardTitle } from "@/components/ui/Card";
import { StatusBadge } from "@/components/ui/StatusBadge";

type Me={firstName:string;lastName:string;email:string;phone:string|null;language:string;kycStatus:string;emailVerified:boolean;twoFactor:boolean};
function Row({icon:Icon,title,subtitle,href,trailing}:{icon:typeof Bell;title:string;subtitle:string;href?:string;trailing?:string}){const content=<div className="flex min-h-16 items-center gap-3 rounded-[16px] px-3 transition-colors hover:bg-[#F5F5F3]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[13px] bg-[#F5F5F3] text-[#101010]/65"><Icon className="h-4.5 w-4.5"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-[#101010]">{title}</span><span className="block text-xs leading-relaxed text-[#101010]/48">{subtitle}</span></span>{trailing&&<span className="text-xs font-semibold text-[#101010]/50">{trailing}</span>}{href&&<ChevronRight className="h-4 w-4 text-[#101010]/30"/>}</div>;return href?<Link href={href}>{content}</Link>:content;}

export default function ParametresPage(){const[me,setMe]=useState<Me|null>(null);const[language,setLanguage]=useState("fr");const[saving,setSaving]=useState(false);const[feedback,setFeedback]=useState<string|null>(null);
useEffect(()=>{fetch("/api/users/me").then(async r=>{if(!r.ok)throw new Error();return await r.json() as Me}).then(data=>{setMe(data);setLanguage(data.language||"fr")}).catch(()=>setFeedback("Impossible de charger les paramètres."));},[]);
const saveLanguage=async()=>{setSaving(true);setFeedback(null);try{const res=await fetch("/api/users/me",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({language})});if(!res.ok)throw new Error();setFeedback("Préférence enregistrée.");}catch{setFeedback("La préférence n'a pas pu être enregistrée.");}finally{setSaving(false)}};
return <div className="min-h-screen bg-[#F5F5F3]"><AppHeader title="Paramètres" subtitle="NEXORA CAPITAL" showBack/><main className="mx-auto w-full max-w-5xl px-4 pb-16 pt-24 sm:px-6 lg:px-10"><div className="mb-8"><h1 className="nx-page-title">Paramètres du compte</h1><p className="nx-page-subtitle">Préférences, conformité et sécurité. Les options affichées correspondent aux capacités réellement actives.</p></div>{feedback&&<div className="mb-5 rounded-[14px] border border-[#101010]/8 bg-white px-4 py-3 text-sm text-[#101010]/65">{feedback}</div>}<div className="grid gap-6 lg:grid-cols-2">
<Card padding="lg"><CardHeader><CardTitle>Préférences</CardTitle></CardHeader><div className="space-y-4"><label className="flex flex-col gap-2 text-sm font-medium text-[#101010]">Langue de l'interface<select value={language} onChange={e=>setLanguage(e.target.value)} className="nx-field h-12 px-4 text-base md:text-sm"><option value="fr">Français</option><option value="en">English</option></select></label><div className="flex items-center justify-between rounded-[14px] bg-[#F5F5F3] px-4 py-3"><div className="flex items-center gap-3"><Globe2 className="h-4 w-4 text-[#101010]/50"/><div><p className="text-sm font-semibold text-[#101010]">Devise d'affichage</p><p className="text-xs text-[#101010]/45">Devise opérationnelle actuelle</p></div></div><span className="font-mono text-xs font-semibold">XOF / FCFA</span></div><Button onClick={saveLanguage} loading={saving} icon={<Languages className="h-4 w-4"/>}>Enregistrer</Button></div></Card>
<Card padding="lg"><CardHeader><CardTitle>Sécurité</CardTitle></CardHeader><div className="space-y-1"><Row icon={KeyRound} title="Mot de passe" subtitle="Modification avec vérification du mot de passe actuel." href="/profil#securite"/><Row icon={ShieldCheck} title="Authentification forte" subtitle="Le champ 2FA historique n'est pas présenté comme protection active tant qu'un fournisseur TOTP n'est pas branché." trailing={me?.twoFactor?"À reconfigurer":"Non activée"}/><Row icon={UserRound} title="Profil" subtitle="Nom, téléphone et informations du compte." href="/profil"/></div></Card>
<Card padding="lg"><CardHeader><CardTitle>Conformité</CardTitle></CardHeader><div className="flex items-center justify-between gap-4 rounded-[16px] bg-[#F5F5F3] p-4"><div><p className="text-sm font-semibold text-[#101010]">Vérification KYC/KYB</p><p className="mt-1 text-xs text-[#101010]/48">Condition d'accès aux opérations financières.</p></div>{me&&<StatusBadge status={me.kycStatus}/>}</div><Link href="/verification" className="mt-4 block"><Button variant="secondary" className="w-full">Gérer les documents</Button></Link></Card>
<Card padding="lg"><CardHeader><CardTitle>Notifications & versements</CardTitle></CardHeader><div className="space-y-1"><Row icon={Bell} title="Notifications opérationnelles" subtitle="Les décisions, paiements, échéances et incidents restent actifs pour la sécurité des opérations." href="/notifications"/><Row icon={WalletCards} title="Moyens de versement" subtitle="Le moyen est choisi lors du versement ou du paiement ; aucun compte bancaire fictif n'est pré-enregistré." href="/dashboard/retrait"/><Row icon={Landmark} title="Coordonnées bancaires" subtitle="Aucune conservation de coordonnées bancaires n'est activée dans ce démonstrateur."/></div></Card>
<Card padding="lg" className="lg:col-span-2"><CardHeader><CardTitle>Confidentialité & documents</CardTitle></CardHeader><div className="grid gap-2 sm:grid-cols-2"><Row icon={FileText} title="Conditions générales" subtitle="Cadre contractuel d'utilisation de la plateforme." href="/cgu"/><Row icon={ShieldCheck} title="Politique de confidentialité" subtitle="Traitement et protection des données personnelles." href="/confidentialite"/></div><p className="mt-4 text-xs leading-relaxed text-[#101010]/45">Les paramètres qui nécessitent un service externe (TOTP, banque liée, préférences marketing multicanales) ne sont pas simulés comme s'ils étaient actifs.</p></Card>
</div></main></div>;
}
