type Status =
  | "PENDING" | "CONFIRMED" | "VERIFIED" | "PAID" | "APPROVED" | "ACTIVE" | "COMPLETED"
  | "REJECTED" | "CANCELLED" | "FAILED" | "EXPIRED" | "DRAFT" | "IN_REVIEW" | "SUBMITTED"
  | "UNDER_REVIEW" | "COMPLEMENT_REQUESTED" | "OFFER_PREPARED" | "OFFER_CONFIRMED" | "PUBLISHED"
  | "SUSPENDED" | "CLOSED_SUCCESS" | "CLOSED_FAIL" | "UPCOMING" | "DUE" | "PARTIAL" | "LATE"
  | "EXECUTED" | "VERIFICATION" | "AVAILABLE" | "WITHDRAWAL_PENDING" | "WITHDRAWN" | "IN_PROGRESS";
const success="bg-[#166534]/10 text-[#166534] ring-1 ring-inset ring-[#166534]/10";const danger="bg-[#C62828]/10 text-[#C62828] ring-1 ring-inset ring-[#C62828]/10";const warning="bg-amber-50 text-amber-800 ring-1 ring-inset ring-amber-200";const info="bg-blue-50 text-blue-700 ring-1 ring-inset ring-blue-100";const neutral="bg-[#F5F5F3] text-[#101010]/60 ring-1 ring-inset ring-[#101010]/6";const accent="bg-[#EFFBDD] text-[#101010] ring-1 ring-inset ring-[#B6FF00]/25";
const c:Record<Status,{label:string;classes:string}>={PENDING:{label:"En attente",classes:warning},CONFIRMED:{label:"Confirmé",classes:success},VERIFIED:{label:"Vérifié",classes:success},PAID:{label:"Payé",classes:success},APPROVED:{label:"Approuvé",classes:success},ACTIVE:{label:"Actif",classes:success},COMPLETED:{label:"Terminé",classes:success},REJECTED:{label:"Rejeté",classes:danger},CANCELLED:{label:"Annulé",classes:danger},FAILED:{label:"Échoué",classes:danger},EXPIRED:{label:"Expiré",classes:danger},DRAFT:{label:"Brouillon",classes:neutral},IN_REVIEW:{label:"En révision",classes:info},SUBMITTED:{label:"Soumis",classes:info},UNDER_REVIEW:{label:"En analyse",classes:info},COMPLEMENT_REQUESTED:{label:"Complément demandé",classes:warning},OFFER_PREPARED:{label:"Conditions à confirmer",classes:warning},OFFER_CONFIRMED:{label:"Conditions confirmées",classes:success},PUBLISHED:{label:"Collecte ouverte",classes:accent},SUSPENDED:{label:"Suspendue",classes:warning},CLOSED_SUCCESS:{label:"Collecte réussie",classes:success},CLOSED_FAIL:{label:"Collecte insuffisante",classes:danger},UPCOMING:{label:"À venir",classes:neutral},DUE:{label:"À régler",classes:warning},PARTIAL:{label:"Partiel",classes:warning},LATE:{label:"En retard",classes:danger},EXECUTED:{label:"Exécuté",classes:success},VERIFICATION:{label:"En vérification",classes:info},AVAILABLE:{label:"Disponible",classes:success},WITHDRAWAL_PENDING:{label:"Versement en vérification",classes:info},WITHDRAWN:{label:"Versé",classes:success},IN_PROGRESS:{label:"En vérification",classes:info}};
export function StatusBadge({status,className=""}:{status:Status|string;className?:string}){const x=c[status as Status]||{label:status,classes:neutral};return <span className={`inline-flex min-h-6 items-center rounded-full px-2.5 py-0.5 text-[11px] font-semibold leading-none ${x.classes} ${className}`}>{x.label}</span>}
