"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleX, FileText, Landmark, LoaderCircle, Pencil, Send, ShieldCheck } from "lucide-react";
import { EntrepriseShell } from "@/components/entreprise/EntrepriseShell";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { formatFCFA, formatRate } from "@/lib/calculations";

type Offer={id:string;type:string;rate:number;ratePeriod:string;duration:number;minTicket:number;maxTicket:number;targetAmount:number;collectedAmount:number;investorCount:number;status:string;publishedAt:string|null};
type Project={id:string;title:string;description:string;sector:string;country:string;city:string|null;totalAmount:number;ownContribution:number;requestedAmount:number;budget:string|null;usageDescription:string|null;status:string;rejectionReason:string|null;createdAt:string;updatedAt:string;submittedAt:string|null;approvedAt:string|null;company:{name:string};offer:Offer|null};
type Terms=Record<string,unknown>;
const STEPS=['Dossier','Analyse','Décision','Structuration','Confirmation','Publication'];
const POS:Record<string,number>={DRAFT:0,SUBMITTED:1,UNDER_REVIEW:1,COMPLEMENT_REQUESTED:1,APPROVED:2,OFFER_PREPARED:3,OFFER_CONFIRMED:4,PUBLISHED:5,REJECTED:2};
const INFO:Record<string,{where:string;todo:string;next:string}>={DRAFT:{where:"Votre dossier est enregistré mais pas encore transmis.",todo:"Finalisez les informations et soumettez-le.",next:"Notre équipe vérifiera le dossier et pourra demander des compléments."},SUBMITTED:{where:"Votre dossier a été reçu.",todo:"Surveillez vos messages et notifications.",next:"Un analyste vérifie la cohérence financière et les justificatifs."},UNDER_REVIEW:{where:"Le dossier est en analyse.",todo:"Aucune action tant qu'aucun complément n'est demandé.",next:"La décision portera sur ce dossier, pas encore sur une offre publiée."},COMPLEMENT_REQUESTED:{where:"Un complément est demandé.",todo:"Rouvrez le dossier et joignez les informations demandées.",next:"Après renvoi, le dossier revient en analyse."},APPROVED:{where:"Le dossier est approuvé.",todo:"Aucune publication directe : attendez la structuration des conditions finales.",next:"Notre équipe prépare une offre distincte à partir de votre proposition et de son analyse."},OFFER_PREPARED:{where:"Les conditions finales sont préparées.",todo:"Comparez-les à votre proposition et confirmez-les uniquement si votre entreprise les accepte.",next:"Après votre confirmation, notre équipe effectue le dernier contrôle avant publication."},OFFER_CONFIRMED:{where:"Votre entreprise a confirmé les conditions finales.",todo:"Aucune action supplémentaire pour le moment.",next:"Notre équipe peut publier l'offre après le dernier contrôle."},PUBLISHED:{where:"L'offre est publiée et la collecte peut recevoir des souscriptions éligibles.",todo:"Suivez engagements, fonds confirmés et échéance de collecte.",next:"Si le seuil minimum est atteint à la clôture, les conditions de décaissement seront vérifiées."},REJECTED:{where:"Le dossier n'a pas été retenu.",todo:"Lisez le motif et corrigez les points concernés avant un nouveau dépôt.",next:"Un nouveau dossier repart dans un nouveau cycle d'analyse."}};
const parse=(raw:string|null)=>{try{const x=JSON.parse(raw||'{}');return x&&typeof x==='object'?x as Record<string,unknown>:{} }catch{return{}}};
export default function Page(){const params=useParams<{id:string}>();const[project,setProject]=useState<Project|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/projects/${params.id}`);if(!r.ok)throw new Error('Dossier inaccessible');setProject(await r.json())}catch(e){setMessage(e instanceof Error?e.message:'Chargement impossible')}finally{setLoading(false)}},[params.id]);useEffect(()=>{void load()},[load]);const parsed=useMemo(()=>parse(project?.budget||null),[project?.budget]);const proposal=(parsed.conditions&&typeof parsed.conditions==='object'?parsed.conditions:{}) as Terms;const finalTerms=(parsed.finalTerms&&typeof parsed.finalTerms==='object'?parsed.finalTerms:null) as Terms|null;const lines=Array.isArray(parsed.lines)?parsed.lines as Array<{label:string;amount:number}>:[];const submit=async()=>{if(!project)return;setMessage('');const r=await fetch(`/api/projects/${project.id}/submit`,{method:'POST'});const j=await r.json().catch(()=>({}));if(!r.ok){setMessage(j.details?.join?.(' ')||j.error||'Soumission impossible');return}setMessage('Dossier transmis à l’équipe d’analyse.');await load()};if(loading)return <EntrepriseShell title="Suivi du dossier"><div className="flex justify-center py-24"><LoaderCircle className="h-8 w-8 animate-spin"/></div></EntrepriseShell>;if(!project)return <EntrepriseShell title="Suivi du dossier"><Card><CircleX className="h-6 w-6 text-[#C62828]"/><p className="mt-3 font-semibold">{message||'Dossier introuvable'}</p></Card></EntrepriseShell>;const info=INFO[project.status]||INFO.DRAFT;const pos=POS[project.status]??0;return <EntrepriseShell title={project.title} subtitle={`${project.company?.name||'Entreprise'} · ${project.sector}${project.city?` · ${project.city}`:''}`} actions={<Link href="/entreprise/dashboard"><Button size="sm" variant="secondary" icon={<ArrowLeft className="h-4 w-4"/>}>Dossiers</Button></Link>}>
 <div className="space-y-6">{message&&<div className="rounded-[14px] border border-[#101010]/8 bg-white p-3 text-sm">{message}</div>}<Card><div className="flex flex-wrap items-center justify-between gap-3"><div><StatusBadge status={project.status}/><p className="mt-2 text-sm text-[#101010]/50">Créé le {new Date(project.createdAt).toLocaleDateString('fr-FR')}</p></div><Badge>{formatFCFA(project.requestedAmount)} recherchés</Badge></div><div className="nx-scroll-strip mt-6">{STEPS.map((s,i)=><div key={s} className={`min-w-[138px] rounded-[14px] border p-3 ${i<pos?'border-[#166534]/15 bg-[#EFFBDD]':i===pos?'border-[#101010] bg-[#101010] text-white':'border-[#101010]/7 bg-[#F5F5F3] text-[#101010]/40'}`}><p className="text-[10px] font-bold uppercase tracking-wide">{i+1}</p><p className="mt-1 text-sm font-semibold">{s}</p></div>)}</div><div className="mt-6 grid gap-3 md:grid-cols-3"><InfoBox label="Où en suis-je ?" text={info.where}/><InfoBox label="Que dois-je faire ?" text={info.todo} accent/><InfoBox label="Que se passera-t-il ensuite ?" text={info.next}/></div><div className="mt-5 flex flex-wrap gap-2">{project.status==='DRAFT'&&<><Link href={`/entreprise/projet/nouveau?draft=${project.id}`}><Button variant="secondary" icon={<Pencil className="h-4 w-4"/>}>Modifier</Button></Link><Button icon={<Send className="h-4 w-4"/>} onClick={()=>void submit()}>Soumettre</Button></>}{project.status==='COMPLEMENT_REQUESTED'&&<Link href={`/entreprise/projet/nouveau?draft=${project.id}`}><Button icon={<Pencil className="h-4 w-4"/>}>Répondre au complément</Button></Link>}{project.status==='OFFER_PREPARED'&&<Link href="/entreprise/conditions"><Button icon={<CheckCircle2 className="h-4 w-4"/>}>Vérifier les conditions finales</Button></Link>}{project.status==='PUBLISHED'&&project.offer&&<Link href="/entreprise/financements"><Button>Suivre la collecte <ArrowRight className="h-4 w-4"/></Button></Link>}{project.status==='REJECTED'&&<Link href="/entreprise/projet/nouveau"><Button>Nouveau dossier</Button></Link>}</div></Card>
 <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-4"><Card><h2 className="text-lg font-bold">Projet</h2><p className="mt-3 whitespace-pre-line text-sm leading-relaxed text-[#101010]/65">{project.description}</p><div className="mt-5 grid gap-2 sm:grid-cols-3"><Mini label="Montant total" value={formatFCFA(project.totalAmount)}/><Mini label="Apport propre" value={formatFCFA(project.ownContribution)}/><Mini label="Financement" value={formatFCFA(project.requestedAmount)}/></div></Card>{lines.length>0&&<Card><h2 className="text-lg font-bold">Budget présenté</h2><div className="mt-3 divide-y divide-[#101010]/7">{lines.map((l,i)=><div key={`${l.label}-${i}`} className="flex justify-between gap-4 py-2.5 text-sm"><span className="text-[#101010]/55">{l.label}</span><b>{formatFCFA(l.amount)}</b></div>)}</div></Card>}</div><div className="space-y-4"><TermsCard title="Votre proposition financière" terms={proposal}/>{finalTerms&&<TermsCard title="Conditions finales structurées" terms={finalTerms} accent/>}{project.rejectionReason&&<Card className="!border-[#C62828]/20 !bg-[#C62828]/5"><h2 className="font-bold text-[#C62828]">Motif / complément</h2><p className="mt-2 text-sm text-[#101010]/65">{project.rejectionReason}</p></Card>}</div></div>
 </div></EntrepriseShell>}
function InfoBox({label,text,accent}:{label:string;text:string;accent?:boolean}){return <div className={`rounded-[14px] p-4 ${accent?'bg-[#EFFBDD]':'bg-[#F5F5F3]'}`}><p className="text-[10px] font-bold uppercase tracking-[.08em] text-[#101010]/45">{label}</p><p className="mt-2 text-sm leading-relaxed text-[#101010]/68">{text}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-[12px] bg-[#F5F5F3] p-3"><p className="text-[10px] uppercase tracking-wide text-[#101010]/40">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>}
function TermsCard({title,terms,accent}:{title:string;terms:Terms;accent?:boolean}){const type=terms.type==='EQUITY'?'Capital':'Dette';const rate=Number(terms.type==='EQUITY'?terms.equityPercentBps??terms.rate:terms.rateBps??terms.rate)||0;const rows=[['Instrument',type],['Rémunération / part',formatRate(rate)],['Période',String(terms.ratePeriod||'—')],['Durée',`${Number(terms.durationMonths??terms.duration??0)} mois`],['Ticket minimum',formatFCFA(Number(terms.minTicket||0))],['Ticket maximum',formatFCFA(Number(terms.maxTicket||0))],['Seuil minimum',formatFCFA(Number(terms.minimumGoal||0))],['Fréquence',String(terms.paymentFrequency||'—')],['Remboursement',String(terms.repaymentMode||'—')],['Garanties',String(terms.guaranteeSummary||'Non renseignées')]];return <Card className={accent?'!border-[#B6FF00]/40 !bg-[#EFFBDD]':''}><div className="flex items-center gap-2"><Landmark className="h-5 w-5"/><h2 className="font-bold">{title}</h2></div><div className="mt-4 space-y-2">{rows.map(([l,v])=><div key={l} className="flex justify-between gap-4 text-xs"><span className="text-[#101010]/45">{l}</span><b className="text-right">{v}</b></div>)}</div></Card>}
