"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, CheckCircle2, CircleDollarSign, Clock3, FileCheck2, Landmark, Search, ShieldCheck, Users, WalletCards } from "lucide-react";
import { AdminShell } from "@/components/admin/AdminShell";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { Modal } from "@/components/ui/Modal";
import { formatFCFA, formatRate } from "@/lib/calculations";

type CoreModule = "dashboard" | "users" | "analysis" | "offers" | "finance" | "commissions" | "audit";

type UserRow = { id:string; email:string; firstName:string; lastName:string; role:string; kycStatus:string; twoFactor:boolean; country:string; createdAt:string };
type CompanyRow = { id:string; name:string; sector:string; country:string; status:string; userId:string; createdAt:string };
type OfferRow = { id:string; type:string; rate:number; ratePeriod:string; duration:number; minTicket:number; maxTicket:number; targetAmount:number; collectedAmount:number; investorCount:number; status:string; startDate:string|null; endDate:string|null; project?: { id:string; title:string; company?: { name:string; userId:string } } };
type ProjectRow = { id:string; title:string; description?:string; sector:string; status:string; requestedAmount:number; ownContribution:number; totalAmount:number; budget:string|null; rejectionReason?:string|null; updatedAt:string; company?: { id:string; name:string; userId:string }; offer?: OfferRow|null };
type InvestmentRow = { id:string; amount:number; status:string; createdAt:string; offer?: { project?: { title:string; company?: { name:string } } }; user?: { firstName:string; lastName:string } };
type PaymentRow = { id:string; reference:string; amount:number; method:string; status:string; createdAt:string };
type DisbursementRow = { id:string; amount:number; tranche:number; status:string; createdAt:string; offer?: { project?: { title:string; company?: { name:string } } } };
type RepaymentRow = { id:string; scheduleDate:string; capitalAmount:number; interestAmount:number; feeAmount:number; paidAmount:number; status:string; offer?: { project?: { title:string; company?: { name:string } } } };
type DistributionRow = { id:string; capitalAmount:number; interestAmount:number; status:string; createdAt:string };
type AuditRow = { id:string; action:string; entity:string; entityId:string|null; details:string|null; createdAt:string; user?: { email:string; firstName:string; lastName:string }|null };
type Ops = { users:UserRow[]; companies:CompanyRow[]; projects:ProjectRow[]; offers:OfferRow[]; investments:InvestmentRow[]; payments:PaymentRow[]; disbursements:DisbursementRow[]; repayments:RepaymentRow[]; distributions:DistributionRow[]; audit:AuditRow[]; generatedAt:string };

type OfferProject = ProjectRow & { company: { id:string; name:string; userId:string }; offer: OfferRow|null };

type Proposal = { type:"DEBT"|"EQUITY"; rateBps:number; ratePeriod:"TOTAL"|"ANNUAL"; durationMonths:number; minTicket:number; maxTicket:number; minimumGoal:number; paymentFrequency:string; repaymentMode:string; graceMonths:number; interestBase:string; earlyRepayment:string; guaranteeSummary:string; guaranteeRank:string; equityPercentBps:number; preMoneyValuation:number; exitHorizonMonths:number };

const parseBudget = (raw:string|null|undefined): Record<string, unknown> => { try { const value=JSON.parse(raw||"{}"); return value&&typeof value==="object"&&!Array.isArray(value)?value:{}; } catch { return {}; } };
const num=(value:unknown, fallback=0)=>{const n=Number(value);return Number.isFinite(n)?n:fallback};
const readProposal=(p:ProjectRow):Proposal=>{const b=parseBudget(p.budget);const raw=((b.finalTerms??b.conditions??{}) as Record<string,unknown>);const type=raw.type==="EQUITY"?"EQUITY":"DEBT";return{type,rateBps:num(raw.rateBps??raw.rate),ratePeriod:raw.ratePeriod==="ANNUAL"?"ANNUAL":"TOTAL",durationMonths:num(raw.durationMonths??raw.duration,6),minTicket:num(raw.minTicket,10000),maxTicket:num(raw.maxTicket,Math.min(5000000,p.requestedAmount)),minimumGoal:num(raw.minimumGoal,p.requestedAmount),paymentFrequency:typeof raw.paymentFrequency==="string"?raw.paymentFrequency:"MONTHLY",repaymentMode:typeof raw.repaymentMode==="string"?raw.repaymentMode:"BULLET",graceMonths:num(raw.graceMonths),interestBase:typeof raw.interestBase==="string"?raw.interestBase:"ORIGINAL_PRINCIPAL",earlyRepayment:typeof raw.earlyRepayment==="string"?raw.earlyRepayment:"ALLOWED",guaranteeSummary:typeof raw.guaranteeSummary==="string"?raw.guaranteeSummary:"",guaranteeRank:typeof raw.guaranteeRank==="string"?raw.guaranteeRank:"",equityPercentBps:num(raw.equityPercentBps??raw.rate),preMoneyValuation:num(raw.preMoneyValuation),exitHorizonMonths:num(raw.exitHorizonMonths??raw.duration,36)}};

const META:Record<CoreModule,{title:string;subtitle:string}>={dashboard:{title:"Pilotage",subtitle:"Priorités, anomalies et prochain mouvement à partir des données réelles de la plateforme."},users:{title:"Utilisateurs",subtitle:"Investisseurs, entreprises, vérifications et sécurité des comptes."},analysis:{title:"Analyse",subtitle:"Instruction des dossiers : compléments, décision et traçabilité."},offers:{title:"Offres",subtitle:"Structuration des conditions, confirmation entreprise, publication et clôture."},finance:{title:"Finances",subtitle:"Encaissements, décaissements, échéanciers et distributions."},commissions:{title:"Commissions",subtitle:"Revenus de plateforme calculés à partir des hypothèses contractuelles du modèle de démonstration."},audit:{title:"Audit",subtitle:"Trace chronologique des actions sensibles et changements d'état."}};

export function AdminCoreModule({module}:{module:CoreModule}){
 const[data,setData]=useState<Ops|null>(null);const[offerProjects,setOfferProjects]=useState<OfferProject[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[action,setAction]=useState<{kind:"reject"|"complement";project:ProjectRow}|null>(null);const[reason,setReason]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [opsRes,offersRes]=await Promise.all([fetch('/api/admin/operations'),module==='offers'?fetch('/api/admin/offers'):Promise.resolve(null)]);if(!opsRes.ok)throw new Error('ops');setData(await opsRes.json());if(offersRes){if(!offersRes.ok)throw new Error('offers');setOfferProjects(await offersRes.json())}}catch{setError("Impossible de charger les données du portail équipe.")}finally{setLoading(false)}},[module]);
 useEffect(()=>{void load()},[load]);
 const post=async(url:string,body?:unknown)=>{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(!res.ok){const j=await res.json().catch(()=>({}));throw new Error(j.error||'Action impossible')}await load()};
 const patch=async(url:string,body:unknown)=>{const res=await fetch(url,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok){const j=await res.json().catch(()=>({}));throw new Error(j.error||'Action impossible')}await load()};
 const doProjectDecision=async()=>{if(!action)return;try{if(action.kind==='reject')await post(`/api/projects/${action.project.id}/reject`,{reason});else await post(`/api/projects/${action.project.id}/request-complement`,{reason});setAction(null);setReason("")}catch(e){setError(e instanceof Error?e.message:"Action impossible")}};
 const stats=useMemo(()=>{if(!data)return null;const pending=data.projects.filter(p=>['SUBMITTED','UNDER_REVIEW','COMPLEMENT_REQUESTED'].includes(p.status));const late=data.repayments.filter(r=>r.status==='LATE');const confirmed=data.investments.filter(i=>i.status==='CONFIRMED').reduce((s,i)=>s+i.amount,0);const collected=data.offers.reduce((s,o)=>s+o.collectedAmount,0);return{pending,late,confirmed,collected}},[data]);
 if(loading)return <AdminShell title={META[module].title} subtitle={META[module].subtitle}><div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(x=><div key={x} className="nx-skeleton h-28"/>)}</div></AdminShell>;
 if(!data||!stats)return <AdminShell title={META[module].title} subtitle={META[module].subtitle}><Card><p className="text-sm text-[#C62828]">{error||"Données indisponibles"}</p></Card></AdminShell>;

 let content:React.ReactNode;
 if(module==='dashboard'){
  const tasks=[...stats.pending.map(p=>({t:`Dossier · ${p.company?.name??'Entreprise'}`,d:p.title,s:p.status})),...data.disbursements.filter(d=>d.status==='PENDING').map(d=>({t:`Décaissement · ${d.offer?.project?.company?.name??'Entreprise'}`,d:formatFCFA(d.amount),s:d.status})),...stats.late.map(r=>({t:`Échéance en retard · ${r.offer?.project?.company?.name??'Entreprise'}`,d:formatFCFA(r.capitalAmount+r.interestAmount+r.feeAmount-r.paidAmount),s:r.status}))].slice(0,10);
  content=<div className="space-y-6"><div className="grid gap-4 md:grid-cols-3"><Metric label="Capital confirmé" value={formatFCFA(stats.confirmed)} icon={<CircleDollarSign/>}/><Metric label="Collecte enregistrée" value={formatFCFA(stats.collected)} icon={<Landmark/>}/><Metric label="Dossiers à traiter" value={String(stats.pending.length)} icon={<Search/>}/></div><div className="grid gap-6 xl:grid-cols-[1.5fr_.5fr]"><Card><SectionTitle title="Que dois-je faire ?" badge={`${tasks.length} priorité(s)`}/><Rows rows={tasks}/></Card><Card><SectionTitle title="Contrôle"/><p className="text-sm leading-relaxed text-[#101010]/60">Les décisions, paiements et changements de bénéficiaire doivent conserver une séparation de tâches et une trace d'audit. Les automatisations ne remplacent pas la validation humaine.</p><div className="mt-5 rounded-[14px] bg-[#EFFBDD] p-4"><p className="text-xs font-semibold text-[#166534]">Ensuite</p><p className="mt-1 text-sm">Traiter les dossiers, rapprocher les flux et surveiller les échéances en retard.</p></div></Card></div></div>;
 }else if(module==='users'){
  content=<div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="Comptes" value={String(data.users.length)} icon={<Users/>}/><Metric label="KYC vérifiés" value={String(data.users.filter(u=>u.kycStatus==='VERIFIED').length)} icon={<CheckCircle2/>}/><Metric label="2FA activée" value={String(data.users.filter(u=>u.twoFactor).length)} icon={<ShieldCheck/>}/></div><Card><SectionTitle title="Comptes et vérifications"/><div className="divide-y divide-[#101010]/7">{data.users.map(u=><div key={u.id} className="grid gap-2 py-3.5 sm:grid-cols-[1.4fr_.7fr_.7fr_auto] sm:items-center"><div><p className="text-sm font-semibold">{u.firstName} {u.lastName}</p><p className="text-xs text-[#101010]/45">{u.email} · {u.country}</p></div><Badge>{u.role}</Badge><StatusBadge status={u.kycStatus}/><Badge variant={u.twoFactor?'success':'warning'}>{u.twoFactor?'2FA':'2FA à activer'}</Badge></div>)}</div></Card></div>;
 }else if(module==='analysis'){
  const projects=data.projects.filter(p=>['SUBMITTED','UNDER_REVIEW','COMPLEMENT_REQUESTED'].includes(p.status));
  content=<div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="À analyser" value={String(projects.length)} icon={<Search/>}/><Metric label="Compléments" value={String(projects.filter(p=>p.status==='COMPLEMENT_REQUESTED').length)} icon={<Clock3/>}/><Metric label="Approuvés" value={String(data.projects.filter(p=>p.status==='APPROVED').length)} icon={<FileCheck2/>}/></div><div className="grid gap-4">{projects.map(p=>{const prop=readProposal(p);return <Card key={p.id}><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><StatusBadge status={p.status}/><Badge>{p.sector}</Badge></div><h2 className="mt-3 text-lg font-bold">{p.company?.name} · {p.title}</h2><p className="mt-1 text-sm text-[#101010]/50">Besoin {formatFCFA(p.requestedAmount)} · apport {formatFCFA(p.ownContribution)}</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><Badge variant="accent">{prop.type==='DEBT'?`${formatRate(prop.rateBps)} ${prop.ratePeriod==='TOTAL'?'total':'/ an'}`:`${formatRate(prop.equityPercentBps)} du capital`}</Badge><Badge>{prop.durationMonths} mois</Badge><Badge>Ticket {formatFCFA(prop.minTicket)}</Badge></div></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={()=>setAction({kind:'complement',project:p})}>Demander un complément</Button><Button size="sm" variant="destructive" onClick={()=>setAction({kind:'reject',project:p})}>Refuser</Button><Button size="sm" onClick={()=>void post(`/api/projects/${p.id}/approve`)}>Approuver le dossier</Button></div></div></Card>})}{!projects.length&&<Card><p className="text-sm text-[#101010]/50">Aucun dossier en file d'analyse.</p></Card>}</div></div>;
 }else if(module==='offers'){
  content=<div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="À structurer" value={String(offerProjects.filter(p=>p.status==='APPROVED').length)} icon={<FileCheck2/>}/><Metric label="À confirmer" value={String(offerProjects.filter(p=>p.status==='OFFER_PREPARED').length)} icon={<Clock3/>}/><Metric label="Publiées" value={String(offerProjects.filter(p=>p.offer?.status==='PUBLISHED').length)} icon={<Landmark/>}/></div><div className="grid gap-4 xl:grid-cols-2">{offerProjects.map(p=>{const proposal=readProposal(p);const offer=p.offer;return <Card key={p.id}><div className="flex items-start justify-between gap-3"><div><StatusBadge status={p.status}/><h2 className="mt-2 text-lg font-bold">{p.company.name}</h2><p className="text-sm text-[#101010]/55">{p.title}</p></div>{offer&&<StatusBadge status={offer.status}/>}</div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="Montant" value={formatFCFA(p.requestedAmount)}/><Mini label={proposal.type==='DEBT'?'Rémunération':'Capital cédé'} value={formatRate(proposal.type==='DEBT'?proposal.rateBps:proposal.equityPercentBps)}/><Mini label="Ticket min." value={formatFCFA(proposal.minTicket)}/><Mini label="Seuil collecte" value={formatFCFA(proposal.minimumGoal)}/></div><div className="mt-4 flex flex-wrap gap-2">{p.status==='APPROVED'&&!offer&&<Button size="sm" onClick={()=>void post('/api/admin/offers',{projectId:p.id})}>Structurer depuis la proposition <ArrowRight className="h-4 w-4"/></Button>}{p.status==='OFFER_PREPARED'&&<Badge variant="warning">En attente de confirmation entreprise</Badge>}{p.status==='OFFER_CONFIRMED'&&offer?.status==='DRAFT'&&<Button size="sm" onClick={()=>void patch(`/api/admin/offers/${offer.id}`,{action:'publish'})}>Publier après dernier contrôle</Button>}{offer?.status==='PUBLISHED'&&<><Button size="sm" variant="secondary" onClick={()=>void patch(`/api/admin/offers/${offer.id}`,{action:'suspend'})}>Suspendre</Button><Button size="sm" onClick={()=>void patch(`/api/admin/offers/${offer.id}`,{action:'close'})}>Clôturer</Button></>}{offer?.status==='SUSPENDED'&&<Button size="sm" onClick={()=>void patch(`/api/admin/offers/${offer.id}`,{action:'resume'})}>Reprendre</Button>}</div></Card>})}</div></div>;
 }else if(module==='finance'){
  const rows=[...data.payments.slice(0,10).map(p=>({t:p.reference,d:`${formatFCFA(p.amount)} · ${p.method}`,s:p.status})),...data.disbursements.slice(0,10).map(d=>({t:`Décaissement · ${d.offer?.project?.company?.name??''}`,d:`Tranche ${d.tranche} · ${formatFCFA(d.amount)}`,s:d.status})),...data.repayments.slice(0,10).map(r=>({t:`Échéance · ${r.offer?.project?.company?.name??''}`,d:`${new Date(r.scheduleDate).toLocaleDateString('fr-FR')} · ${formatFCFA(r.capitalAmount+r.interestAmount+r.feeAmount)}`,s:r.status}))];
  content=<div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="Paiements confirmés" value={formatFCFA(data.payments.filter(p=>p.status==='CONFIRMED').reduce((s,p)=>s+p.amount,0))} icon={<WalletCards/>}/><Metric label="Décaissements exécutés" value={formatFCFA(data.disbursements.filter(d=>d.status==='EXECUTED').reduce((s,d)=>s+d.amount,0))} icon={<Landmark/>}/><Metric label="Distributions" value={formatFCFA(data.distributions.filter(d=>['AVAILABLE','WITHDRAWN'].includes(d.status)).reduce((s,d)=>s+d.capitalAmount+d.interestAmount,0))} icon={<CircleDollarSign/>}/></div><Card><SectionTitle title="Flux récents"/><Rows rows={rows}/></Card></div>;
 }else if(module==='commissions'){
  const funded=data.offers.filter(o=>['CLOSED_SUCCESS','PUBLISHED','SUSPENDED'].includes(o.status));const initial=funded.reduce((s,o)=>s+Math.round(o.collectedAmount*.06),0);const follow=data.repayments.reduce((s,r)=>s+r.feeAmount,0);
  content=<div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="Commission initiale théorique" value={formatFCFA(initial)} icon={<CircleDollarSign/>}/><Metric label="Frais de suivi échéancés" value={formatFCFA(follow)} icon={<WalletCards/>}/><Metric label="CA théorique suivi" value={formatFCFA(initial+follow)} icon={<Landmark/>}/></div><Card><SectionTitle title="Lecture financière"/><p className="text-sm leading-relaxed text-[#101010]/60">Ces montants utilisent les hypothèses commerciales 6 % + 2 %/an du modèle de démonstration. Ils ne doivent pas être confondus avec des sommes facturées ou encaissées tant qu'une couche de facturation/comptabilité n'est pas branchée.</p></Card></div>;
 }else{
  content=<Card><SectionTitle title="Journal d'audit" badge={`${data.audit.length} événement(s)`}/><div className="divide-y divide-[#101010]/7">{data.audit.map(a=><div key={a.id} className="grid gap-1 py-3.5 sm:grid-cols-[1fr_.6fr_.7fr]"><div><p className="text-sm font-semibold">{a.action}</p><p className="text-xs text-[#101010]/45">{a.entity}{a.entityId?` · ${a.entityId}`:''}</p></div><p className="text-xs text-[#101010]/50">{a.user?.email??'Système'}</p><p className="text-xs text-[#101010]/45 sm:text-right">{new Date(a.createdAt).toLocaleString('fr-FR')}</p></div>)}</div></Card>;
 }
 return <AdminShell title={META[module].title} subtitle={META[module].subtitle}>{error&&<div className="mb-4 rounded-[14px] border border-[#C62828]/20 bg-[#C62828]/5 p-3 text-sm text-[#C62828]">{error}</div>}{content}<Modal open={!!action} onClose={()=>{setAction(null);setReason("")}} title={action?.kind==='reject'?'Refuser le dossier':'Demander un complément'}><label className="text-sm font-semibold">Motif / éléments attendus</label><textarea className="nx-field mt-2 min-h-32 p-3 text-sm" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Expliquez précisément la décision ou les pièces attendues…"/><div className="mt-4 flex gap-2"><Button variant="secondary" className="flex-1" onClick={()=>setAction(null)}>Annuler</Button><Button variant={action?.kind==='reject'?'destructive':'primary'} className="flex-1" disabled={!reason.trim()} onClick={()=>void doProjectDecision()}>Confirmer</Button></div></Modal></AdminShell>;
}

function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <Card><div className="flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.08em] text-[#101010]/42">{label}</p><p className="mt-2 text-xl font-bold tracking-[-.03em] sm:text-2xl">{value}</p></div><span className="grid h-10 w-10 place-items-center rounded-[12px] bg-[#EFFBDD] [&>svg]:h-5 [&>svg]:w-5">{icon}</span></div></Card>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-[12px] bg-[#F5F5F3] p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#101010]/42">{label}</p><p className="mt-1 text-sm font-bold leading-snug">{value}</p></div>}
function SectionTitle({title,badge}:{title:string;badge?:string}){return <div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-lg font-bold">{title}</h2>{badge&&<Badge variant="accent">{badge}</Badge>}</div>}
function Rows({rows}:{rows:Array<{t:string;d:string;s:string}>}){return <div className="divide-y divide-[#101010]/7">{rows.length?rows.map((r,i)=><div key={`${r.t}-${i}`} className="flex items-start justify-between gap-4 py-3.5"><div className="min-w-0"><p className="truncate text-sm font-semibold">{r.t}</p><p className="mt-1 text-xs text-[#101010]/48">{r.d}</p></div><StatusBadge status={r.s}/></div>):<p className="py-10 text-center text-sm text-[#101010]/45">Aucune action dans cet état.</p>}</div>}
